### ISSUE TITLE
Documentation states that 'branch' is required in a git resource, but is it really?

### ISSUE THREAD

**Issue by kdvolder** [concourse/git-resource#108]
This example works fine even though it doesn't specify a branch.

```
resources:
- name: my-repo
  type: git
  source:
    uri: https://github.com/spring-projects/sts4.git
jobs:
- name: do-stuff
  plan:
  - get: my-repo
```

Note 1: Similar example here in a often used tutorial: https://github.com/starkandwayne/concourse-tutorial/blob/master/05_pipeline_task_hello_world/pipeline.yml

Note 2: We are asking this question because our linter currently flags an error on the git resource source when its missing a 'branch' attribute. We'd like to know whether we should really check this constraint or not. The tutorial example seems to suggest its not required, but the docs disagree.
