### ISSUE TITLE
parameter replacement works from file but fails from inline cat with "Private keys with passphrases are not supported."

### ISSUE THREAD

**Issue by mbjelac** [concourse/git-resource#111]
Possibly but not quite a duplicate of #88.

I am injecting a private RSA key.

My pipeline:

```
resources:
  - name: source-code
    type: git
    source:
      uri: git@somewhere:foo/bar.git
      branch: master
      private_key: {{private-repo-key}}

... jobs ...
```

I generated the RSA key without a passphrase like this:

```
ssh-keygen -t rsa -b 4096 -q -N "" -f "/sshpath/ci_rsa" -C "my@e-mail.com"
```

This works:

1. Place the private key in `key.yml`:
    ```
    private-repo-key: |
      -----BEGIN RSA PRIVATE KEY-----
      BLAHBLAHBLAH
      ....
      BLAHBLAHBLAH
      -----END RSA PRIVATE KEY-----
    ```
1. Set the pipeline with Fly:
    ```
    fly -t lite set-pipeline --config mypipeline.yml --pipeline mypipeline --load-vars-from "key.yml"
    ```

I see from the diff that the RSA key has been injected in the pipeline.

-----

This doesn't work:

1. Set the pipeline with Fly:
    ```
    fly -t lite set-pipeline --config mypipeline.yml --pipeline mypipeline --var "private-repo-key=$(cat /sshpath/ci_rsa)"
    ```

I see from the diff that the `cat` command was injected to the pipeline like this:

```
resources:
  - name: source-code
    type: git
    source:
      branch: master
      private_key: $(cat /sshpath/ci_rsa)
      uri: ...
```

Which seems wrong to me because I could have hardcoded that command in the pipeline myself without using parameter replacement...

This pipeline fails with: `Private keys with passphrases are not supported.`

I tried the `cat` command on the console (copy-paste from the diff) and it works.

What am I doing wrong?
