### ISSUE TITLE
[put] force pushing fails if no changes present

### ISSUE THREAD

**Issue by drahnr** [concourse/git-resource#136]
Force pushing fails if 

```
On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working tree clean
```

and the job fails.

If there are changes the repository everthing goes well and the job succeeds.

```
  - name: doc-coaster
    build_logs_to_retain: 20
    public: true
    plan:
    - aggregate:
      - get: doc-coaster
      - get: coaster
        params: {depth: 1}
        trigger: true
      - get: container
        trigger: true
        passed: [test-coaster]
    - task: gen-doc
      image: container
      config:
        platform: linux
        inputs:
        - name: coaster
        - name: doc-coaster
        outputs:
        - name: doc-coaster-updated
        run:
          path: sh
          args:
          - -exc
          - |
            cd coaster
            cargo doc --no-deps
            cd -
            git clone doc-coaster doc-coaster-updated
            rm -rf doc-coaster-updated/*
            cp -rf coaster/target/doc/* doc-coaster-updated/
            cd doc-coaster-updated
            echo "<meta http-equiv=refresh content=0;url=coaster/index.html>" > index.html
            git config --global user.email "jack@blah.io"
            git config --global user.name "foo ar"
            git add -A
            git commit -m"doc/automatic: update"
    - put: doc-coaster
params: { repository: doc-coaster-updated, force: true }
```

https://ci.spearow.io/teams/spearow/pipelines/juice/jobs/doc-greenglas/builds/3
