### ISSUE TITLE
Reusing resource with filters ?

### ISSUE THREAD

**Issue by pfijalki** [concourse/git-resource#156]
Let's say we have configuration of resource

```
    - name: source-master
      type: git
      source:
        ...
        branch: master
        tag_filter: release*
```

and two jobs job-push and job-listen which respectively push to and get from source-master. 

While getting on resource flag tag_filter should be respected (releasing only new version when commit is done for tag matching filter), but job-push makes 'put' to the same resource triggering new version of it. So job-listen will pick new version regardless of tag_filter match result

Is this behavior bug or feature ?;-)
