### ISSUE TITLE
 Could not read from remote repository

### ISSUE THREAD

**Issue by phynias** [concourse/git-resource#159]
> resource script '/opt/resource/check []' failed: exit status 128
> 
> stderr:
> Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
> Cloning into '/tmp/git-resource-repo-cache'...
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

------

ok so i have tried all the fixes people have tried that i could find.
i added the garden_dns_server option to the worker in case i was having some weird dns issues.
i've hijacked the pipeline to get the cert file and test it by hand. i've tried adding the key with | and |-. the weird thing is it worked before. it seems like it works for a time and then suddenly doesn't. prior to today this happened a couple of days ago and i got so frustrated i blew away my aws instance and started all over and it worked. then i look today and it stopped working again.
i used that key on that repo all the time, concourse is the only thing that has a problem.

```
resources:
  resource git-concourse-build-edge-image has been added:
    name: git-concourse-build-edge-image
    type: git
    source:
      branch: master
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        ....
        -----END RSA PRIVATE KEY-----
      uri: git@github.com:xxxx/xxxx.git

  resource send-edge-image has been added:
    name: send-edge-image
    type: docker-image
    source:
      email: xxxx
      password: xxxx
      repository: xxxx
      username: xxxx

jobs:
  job build-edge-image has been added:
    name: build-edge-image
    public: true
    serial: true
    plan:
    - get: git-concourse-build-edge-image
      trigger: true
    - put: send-edge-image
      params:
        build: git-concourse-build-edge-image
```
