### ISSUE TITLE
`[ci skip]` not respected

### ISSUE THREAD

**Issue by flawedmatrix** [concourse/git-resource#18]
commits with `[ci skip]` are now showing up inside our git resources and triggering builds looking at [the repo in question is public](github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release) should allow reproduction of the issue.

Local git version: `git version 2.5.0`
Version of git inside container which made commit: `git version 1.9.1`

**Comment by xoebus** [comment]
IIRC this was caused by the commit being created from a `put` step which skips that check. Please re-open if this was not the case.

**Comment by MatthiasWinzeler** [comment]
@xoebus Can you clarify this for others running into the same problem - so if a commit with `[ci skip]` is pushed from a `put` step, it will still trigger other jobs (when defined as trigger there)?

I have a job that triggers from a certain repo, does some changes to the repo and then commits & pushes these changes back to the repo. Because the push triggers again, I'm caught in an endless loop. I tried with `[ci skip]` in the commit message, but the job still triggers.

Do you know a solution for this? Should I somehow use `ignore-paths`?

**Comment by xoebus** [comment]
Try pushing to a different but identically configured resource.

**Comment by MatthiasWinzeler** [comment]
Thanks, that did the trick!

How the relevant parts of my working pipeline look like:
```
jobs:
- name: create boshrelease
  public: false
  serial: true
  plan:
...
  - get: boshrelease-trigger
    trigger: true
...
  - task: create-final-boshrelease
...
  - put: boshrelease-put
      params:
        repository: boshrelease-repo-output
        rebase: true
...

resources:
- name: boshrelease-put
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
- name: boshrelease-trigger
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
```

Note that the `task` copies the modified repo from the `input` to `boshrelease-repo-output` which the `put` then uses.

**Comment by MatthiasWinzeler** [comment]
I found out that with the above solution, triggering the job manually after a successful run will fail. This is because `boshrelease-put` will commit and push the change with `[ci skip]` which the separate `boshrelease-trigger` resource will not pick up. When a manual job is triggered now, the last commit will not exist in `boshrelease-trigger` and the put at the end of the job fails because of a merge conflict.

To solve this, I include the resource we're pushing `boshrelease-put` also as `get`. This repo will contain the latest commits and serves as starting repo for the new changes. `boshrelease-trigger` is only used for triggering and is no longer used by the jobs.

My final job looks like this:
```
jobs:
- name: create boshrelease
  public: false
  serial: true
  plan:
...
  - get: boshrelease-trigger
    trigger: true
  - get: boshrelease-put
...
  - task: create-final-boshrelease
...
  - put: boshrelease-put
      params:
        repository: boshrelease-repo-output
        rebase: true
...

resources:
- name: boshrelease-put
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
- name: boshrelease-trigger
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
```

**Comment by krishicks** [comment]
I don't like this solution because it is not obvious that Concourse will in some cases disregard the rules that the user has configured on a resource.

I have configured a resource such that new resources should not be discovered given it is tagged as such. Still, Concourse decides to ignore that rule when doing a dependent get, which isn't what I want in any case here.

This is a not-easily-discoverable bug.

**Comment by xoebus** [comment]
This behavior is core to how Concourse reasons about the semantics of streams of resource versions flowing through a pipeline. 

I would advise against any use of `[ci skip]`. It leads to nonsense and headaches that resemble the need for a `disable_ci_skip` parameter.

**Comment by krishicks** [comment]
The headache here was me discovering that I have to configure an additional resource to model this, and that it leaves me in a state where I'm using a hack to achieve my goal.

I want to be able to say in a very clear way that an arbitrary `put` is put-*only*, i.e. no dependent get because Concourse doesn't get to decide for my resource when a new version exists. Resources get to decide when a new version exists. Having to define a separate resource for that *sucks and is stupid* because this secondary resource is only *treated* as a put-only resource, but still can be used as a `get` resource when that is not what I want to describe.

**Comment by youngm** [comment]
I attempted to follow the final pattern put forth by @MatthiasWinzeler and that didn't work for me because the triggered resource version frequently came up as different than the non triggered version.  So, if I committed new code the trigger would detect the commit but the non triggered that I was supposed to be using wouldn't have the same commit version.  I assume this is because of differences in check cycle.  So, this isn't a viable workaround for me.

**Comment by youngm** [comment]
FWIW, I worked around my latest issue by doing a pull and a push back as the first step in my triggered job.  Which works for me because I only want [ci skip] to skip auto triggered builds.  We'll see how long this hack works.  Probably not long since this issue seems to be a pretty big rat hole. :)


So here is the pseudo config for what worked for me in case it is useful for anyone else:

```
jobs:
- name: create boshrelease
  public: false
  serial: true
  plan:
...
  - get: boshrelease
    trigger: true
  - task: pull-latest-boshrelease
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
      inputs:
      - name: boshrelease
      outputs:
      - name: boshrelease-latest
      run:
        path: sh
        args:
        - -exc
        - |
          cd boshrelease
          git pull
          cd ..
          git clone boshrelease boshrelease-latest
  - put: boshrelease
    params:
      repository:  boshrelease-latest
...
  - task: create-final-boshrelease
...
  - put: boshrelease-put
      params:
        repository: boshrelease-repo-output
        rebase: true
...

resources:
- name: boshrelease
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
- name: boshrelease-put
  type: git-resource
  source:
    uri: <boshrelease-repo-url>
    ...
```

**Comment by Yacine-A** [comment]
@giner I have the same issue, and this is a major set back. Any progress on it?

**Comment by chrishiestand** [comment]
I'm having a problem with one pipeline not respecting `[ci skip]`, even though a nearly identical pipeline does seem to respect it. However my issue is with only a single job in the build/pipeline, and a single git resource, so I'm not sure if it is related to this issue.

More details about my problem (help requested please) here:
https://discuss.concourse-ci.org/t/git-resource-infinite-loop-with-ci-skip/524

**Comment by swtch1** [comment]
I have "re-opened" the issue on [221](https://github.com/concourse/git-resource/issues/221).

**Comment by jacek-rzrz** [comment]
For those still running into this issue now: @MatthiasWinzeler workaround of introducing a separate `put` resource does work, however I learned the hard way that `put` and `trigger` resource configurations mustn't be identical.

When they are identical, [resource cache](https://medium.com/concourse-ci/concourse-resource-volume-caching-7f4eb73be1a6) treats them as one resource, resulting in an unconditional new version of the trigger resource on each put 😤.

So for example:

```yml
- name: repo-trigger
   type: git
   source: &git
     uri: git@github.com:example/example.git
     private_key: ((deploy-key))
     branch: main

- name: repo-put
   type: git
   source:
     <<: *git
     ignore_paths: [ make-it-different ] # this is the magic line
```
