### ISSUE TITLE
Specifying version (ref / tag)

### ISSUE THREAD

**Issue by prein** [concourse/git-resource#190]
Hi,

I'm finding the way to specify version unclear and couldn't figure it out without digging in the code.
I also can't get it to work :(

Would someone be so kind to try to help me out by providing documentation perhaps?

My pipeline goes like this
```
resources:
- name: source-code-foo
  type: git
  source:
    branch: develop
    uri: https://foo.git
    password: redacted 
    username: redacted
jobs:
- name: build
  plan:
  - get: source-code-foo
    trigger: false
    version:
      tag: test-tag-123
```
When I trigger the pipeline it gets stuck waiting for resource saying pinned version is not available.
I tried also setting ref to a commit sha and setting ref to "HEAD". Same problem. I've tried running fly check-release. Same. What am I doing wrong?

Apart from "how to make it work?" there are other questions that arise in my head:
* why is it that I specify "source.branch" in resources and "version.tag" under jobs?
* does "trigger" setting influence version polling?

Thanks in advance for looking into it
