### ISSUE TITLE
dont find all tags

### ISSUE THREAD

**Issue by obeyler** [concourse/git-resource#222]
I've try to use it on eclipse che repo
on  https://github.com/eclipse/che/tags we can see that tags 6.x exist 
![image](https://user-images.githubusercontent.com/23224162/47303101-5bf85180-d623-11e8-8000-4edefe2695d4.png)

but resource doesn't manage to find greater that 5.9.0
![image](https://user-images.githubusercontent.com/23224162/47302835-c361d180-d622-11e8-8534-fd002af7ab67.png)
```
- name: che-release
  type: git
  source:
    uri: https://github.com/eclipse/che.git
    tag_filter: "[0-9].*"
```
