### ISSUE TITLE
Builds not triggering on new commits

### ISSUE THREAD

**Issue by luispabon** [concourse/git-resource#229]
I've set up a very simple pipeline that builds several docker images off dockerfiles from a single repository. 

As you can see, git resource is certainly aware of a new commit, but it has no information about it nor did it trigger a new build:

![image](https://user-images.githubusercontent.com/6388823/49478084-bede2a80-f816-11e8-9014-89e7fb1f12c9.png)

I would have expected all the builds to have triggered (since I haven't yet set up any exclusions), yet none did.

I'm completely new to Concourse so I'm certain I'm missing a trick here, but nothing obvious jumps out at me.

This is the pipeline:

```yaml
version: 2.1
resources:
# Repository
- name: base-images
  type: git
  check_every: 5m
  source:
    uri: https://github.com/phpdocker-io/base-images.git
    branch: master

# Periodic triggers to get daily builds
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 12:45 AM

# Docker hub repositories
- name: phpdockerio/php7-cli
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php7-cli

- name: phpdockerio/php7-fpm
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php7-fpm

- name: phpdockerio/php71-cli
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php71-cli

- name: phpdockerio/php71-fpm
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php71-fpm

- name: phpdockerio/php72-cli
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php72-cli

- name: phpdockerio/php72-fpm
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-user}}
    password: {{docker-hub-password}}
    repository: phpdockerio/php72-fpm

jobs:
- name: php 7.0
  public: true
  plan:
  - get: base-images
    trigger: true
  - get: after-midnight
    trigger: true
  - put: phpdockerio/php7-cli
    params:
        build: base-images/php/7.0/cli
  - put: phpdockerio/php7-fpm
    params:
        build: base-images/php/7.0/fpm

- name: php 7.1
  public: true
  plan:
  - get: base-images
    trigger: true
  - get: after-midnight
    trigger: true
  - put: phpdockerio/php71-cli
    params:
        build: base-images/php/7.1/cli
  - put: phpdockerio/php71-fpm
    params:
        build: base-images/php/7.1/fpm

- name: php 7.2
  public: true
  plan:
  - get: base-images
    trigger: true
  - get: after-midnight
    trigger: true
  - put: phpdockerio/php72-cli
    params:
        build: base-images/php/7.2/cli
  - put: phpdockerio/php72-fpm
    params:
        build: base-images/php/7.2/fpm
```

**Comment by bs76** [comment]
The same issue here CC 4.2.2. A downgrade to git resource `1.0` solves the issue and actually triggers pipelines all the time.
```
- name: git 
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: 1.0.0
```

**Comment by vito** [comment]
I don't think this is a bug with the resource, as it's doing its job and detected the versions. This could be an issue with your deployment causing scheduling to hang or something. In any case, this may be better off in the [forums](https://discuss.concourse-ci.org) instead.

**Comment by bs76** [comment]
Here is part of the pipeline that did not work.
```yaml
![cc_capture](https://user-images.githubusercontent.com/5235784/51906236-f5be6000-23c3-11e9-8292-c097a30d607b.png)

resources:
- name: screening
  type: git
  source:
    uri: git@github.com:xrepo/screening.git
    private_key: ((xrepo-github-key))
    branch: ((branch))

- name: client
  type: git
  source:
    uri: git@github.com:xrepo/client.git
    private_key: ((xrepo-github-key))
    branch: ((branch))

- name: esm
  type: git
  source:
    uri: git@github.com:xrepo/external-services-mock.git
    private_key: ((xrepo-github-key))
    branch: develop

# Repository infra provides helper scripts. New commits to the repo never trigger
# a new build.
- name: infra
  type: git
  source:
    uri: git@github.com:xrepo/infra.git
    private_key: ((xrepo-github-key))
    branch: master

- name: locks
  type: pool
  source:
    uri: git@github.com:xrepo/infra.git
    branch: locks
    pool: merlon
    private_key: ((xrepo-github-key))

- name: test-env
  type: helm
  source:
    cluster_url: ((k8s-cluster-endpoint))
    cluster_ca: ((k8s-cluster-ca))
    namespace: test

- name: build-number
  type: semver
  source:
    driver: git
    uri: git@github.com:xrepo/infra.git
    branch: version
    file: version
    private_key: ((xrepo-github-key))

# Latest build manifest for the specified branch.
- name: manifest-branch
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: manifests/((branch))/latest.json

# Build manifests for the specified branch.
- name: manifest-build
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    regexp: manifests/((branch))/(\d+)\.json$

# Sub-repository manifest for screening.
- name: manifest-screening
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: _tmp/((branch))-screening.json

# Sub-repository manifest for client.
- name: manifest-client
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: _tmp/((branch))-client.json

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-web-hook))

jobs:
- name: build-screening
  build_logs_to_retain: 100
  serial: true
  plan:
  - aggregate:
    - get: screening
      trigger: true
    - get: infra
  - do:
    - task: build-screening
      file: screening/ci/build.yaml
      privileged: true
    - put: locks
      params:
        claim: screening
    - do:
      - aggregate:
        - task: upload-coverage
          file: infra/pipelines/tasks/upload-artifacts.yaml
          input_mapping:
            artifacts: coverage
            target-path: screening
          params:
            BUCKET: builds/coverage
            TARGET_PATH_FILE: .git/ref
        - task: upload-artifacts
          file: infra/pipelines/tasks/upload-artifacts.yaml
          input_mapping:
            artifacts: tgz-artifacts
        - do:
          - task: filter-images
            file: infra/pipelines/tasks/filter-images.yaml
            input_mapping:
              repo: screening
          - task: build-images
            file: infra/pipelines/tasks/build-images.yaml
            privileged: true
            input_mapping:
              repo: screening
              docker-staging: missing-images
      ensure:
        put: locks
        params:
          release: locks
    - task: prepare-manifest
      file: infra/pipelines/tasks/prepare-manifest.yaml
      params:
        GIT_REPO: screening
        BRANCH: ((branch))
      input_mapping:
        repo: screening
    - put: manifest-screening
      params:
        file: ./manifest/manifest.json
    on_failure:
      do:
      - task: prepare-alert
        file: infra/pipelines/tasks/prepare-alert.yml
        input_mapping:
          repo1: screening
      - put: slack-alert
        params:
          icon_emoji: ':scream:'
          channel: '#build-investigations'
          channel_file: alert/channels
          text_file: alert/message
          always_notify: true
          text: |
            $TEXT_FILE_CONTENT
            *Build details:* <https://location/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.11.0-1

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.3.0

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2
    

```

Also pls check the attached screen capture: commits 49d432, 16736a0, e44200cdbe, 8ab2c7dd, 34a121 did not trigger the build
