### ISSUE TITLE
out merge: true fails if remote branch is missing

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/git-resource#230]
example:
```yaml
  - put: git-resource
    params:
      repository: dir-path
      merge: true
```

if the remote branch does not yet exist, the push fails

I need it to work if the remote branch doesn't exist yet. The whole reason I'm using merge in the first place is so IF it exists, it will attempt to merge it.

Edit: by the way, the docs say IF it fails to push, it will attempt to merge, this is why I believe this behavior is a bug... it shouldn't be trying to merge before trying first.
