### ISSUE TITLE
recursive submodules are not cloned

### ISSUE THREAD

**Issue by baszalmstra** [concourse/git-resource#251]
I just upgraded from Concourse v4.2.2 to v5.0.1. Since this update recursive submodules are no longer cloned. Submodules themselves are checked out just fine but their submodules are not cloned. 

One example is breakpad which has a recursive submodules required to build the project. In version v4.2.2 the output would yield something like:
```
Submodule 'external/breakpad/source' (<redacted>) registered for path 'external/breakpad/source'
Cloning into '/tmp/build/get/external/breakpad/source'...
Submodule path 'external/breakpad/source': checked out 'a78ee23927cb3a5d4040e75c2b8a37c2f1c6be39'	
Submodule 'src/third_party/lss' (<redacted>) registered for path 'external/breakpad/source/src/third_party/lss'
Cloning into '/tmp/build/get/external/breakpad/source/src/third_party/lss'...
Submodule path 'external/breakpad/source/src/third_party/lss': checked out 'e6527b0cd469e3ff5764785dadcb39bf7d787154'
```

Version v5.0.1 outputs:
```
Submodule 'external/breakpad/source' (<redacted>) registered for path 'external/breakpad/source'
Cloning into '/tmp/build/get/external/breakpad/source'...
Submodule path 'external/breakpad/source': checked out 'a78ee23927cb3a5d4040e75c2b8a37c2f1c6be39'
Entering 'external/breakpad/source'
fetch: Fetching reference HEAD
WARNING: 'git lfs checkout' is deprecated and will be removed in v3.0.0.
'git checkout' has been updated in upstream Git to have comparable speeds
to 'git lfs checkout'.
```

Nothing related to the recursive `lss` submodule.

I've not specified any submodule parameters in the config:

```
- name: source
  type: git
  source:
    branch: ((branch))
    uri: <redacted>
    private_key: {{gitlab-private-key}}
    ignore_paths: 
    - ci/pipelines/**
    - images/**
```

And also none in the `get` step:

```
- get: source
``` 

Explicitly adding `submodule_recursive` doesn't change anything: 

```
- get: source
  params: { submodule_recursive: true }
```

This currently breaks a lot of my pipelines. Reading through the source did not yield any solution. Any fix or workaround would be greatly appreciated!

**Comment by vito** [comment]
Is this the same as https://github.com/concourse/git-resource/issues/246?

**Comment by baszalmstra** [comment]
> 
> 
> Is this the same as #246?

No, I also ran into that issue, but fixed it by ensuring the paths and the names are the same in my .gitmodule file.

**Comment by baszalmstra** [comment]
I created a very minimal repro: https://github.com/baszalmstra/concourse-git-concourse-recursive-repro.

The pipeline simply clones a repository containing a single submodule which in turn contains recursive submodules:

```
resources:
- name: source
  type: git
  source:
    uri: https://github.com/baszalmstra/concourse-git-concourse-recursive-repro.git
    
jobs:
- name: test
  plan:
    - get: source
```

The build output of test shows that the recursive submodules are not cloned:

```
Cloning into '/tmp/build/get'...
fetch: Fetching reference HEAD
WARNING: 'git lfs checkout' is deprecated and will be removed in v3.0.0.	
'git checkout' has been updated in upstream Git to have comparable speeds
to 'git lfs checkout'.
71eff0a initial commit
Submodule 'header-parser' (https://github.com/baszalmstra/header-parser.git) registered for path 'header-parser'
Cloning into '/tmp/build/get/header-parser'...
Submodule path 'header-parser': checked out '56e748e62a0fadec3664d34770c99111aa8bd4e7'
Entering 'header-parser'
fetch: Fetching reference HEAD
WARNING: 'git lfs checkout' is deprecated and will be removed in v3.0.0.
'git checkout' has been updated in upstream Git to have comparable speeds
to 'git lfs checkout'.
```

Next I tried to use a different version of the git resource. Here is my summary of which version cloned the recursive submodules and which didn't:

Version|Works
-------|-----
1.0.0   | ☑ 
1.0.1   | ☑ 
1.1.0   | ❌
1.1.1   | ❌
1.2.0   | ❌
1.3.0   | ❌

So it appears this functionality broke with the 1.1.0 release of this resource.

**Comment by vito** [comment]
I opened #255 in an attempt to fix this and clean up a few things, but I haven't had time to verify it. If you have time to try it out, I've pushed it to `vito/git-resource:pr-255`:

```yaml
resource_types:
- name: git
  type: registry-image
  source: {repository: vito/git-resource, tag: pr-255}
```
