### ISSUE TITLE
Regression with clone repos with submodules

### ISSUE THREAD

**Issue by taylorsilva** [concourse/git-resource#259]
Current version of the git-resource (both alpine and ubuntu versions) are returning this error:

```
git submodule update --init --no-fetch --recursive fixtures/go16_dependencies/Godeps/_workspace/src/github.com/ZiCog/shiny-thing
error: pathspec 'fixtures/go16_dependencies/Godeps/_workspace/src/github.com/ZiCog/shiny-thing' did not match any file(s) known to git.
```

Appears to be an issue with the submodule in the repo. You can reproduce the issue with this pipeline:

```yaml
resource_types:
  - type: registry-image
    name: old-git
    source:
      repository: "concourse/git-resource"
      tag: "1.2"
  - type: registry-image
    name: current-alpine-git
    source:
      repository: "concourse/git-resource"

resources:
  - type: old-git
    name: repository
    source: { uri: 'https://github.com/cloudfoundry/go-buildpack' }
  - type: current-alpine-git
    name: current-repository
    source: { uri: 'https://github.com/cloudfoundry/go-buildpack' }

jobs:
  - name: previous-git-resource
    public: true
    plan:
      - get: repository
  - name: current-git-resource
    public: true
    plan:
      - get: current-repository
```
