### ISSUE TITLE
Enable pinning to a commit hash / revision

### ISSUE THREAD

**Issue by michaellihs** [concourse/git-resource#266]
We have the following problem: for deploying a service in K8S, we use the official [helm-charts](https://github.com/helm/charts) repository as a git resource in our Concourse pipeline. We would like to pin the repository to a certain commit to enable testing of newer versions before we roll them out into production.

The problem with the helm-charts repo is that there are no (version) tags, so we cannot pin to a tag.

It would be great to have a feature like:

```yaml
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:concourse/git-resource.git
    revision: 4788c4334602aeb4edb8fe141168382c351b407e
```

I'd spend time for a PR but wanted to ask whether this feature makes sense for you and whether you would accept a PR for that.

**Comment by deadNightTiger** [comment]
You can pin the version in your `get` step: https://concourse-ci.org/get-step.html#get-step-version

```
- get: source-code
  version:
    ref: 4788c4334602aeb4edb8fe141168382c351b407e
```

**Comment by vito** [comment]
yep, also `version` on the resource itself:

```
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:concourse/git-resource.git
  version:
    ref: 4788c4334602aeb4edb8fe141168382c351b407e
```
