### ISSUE TITLE
paths filter does not work in conjunction with tag_filter

### ISSUE THREAD

**Issue by sfunkhouser** [concourse/git-resource#292]
Attempting to use the following `resource` in my concourse pipeline:

```
- name: my-app-helm-chart
  type: git
  source:
    tag_filter: '*'
    paths:
    - helm/my-app/Chart.yaml
...
```

However, the `paths` parameter is not being respected and instead just all tags are being used for the job. 

The documentation does not state these cannot be used together, although reading through the check resource it seems the `paths` filter is not used when `tag_filter` is set.
