### ISSUE TITLE
push without submodules

### ISSUE THREAD

**Issue by HoffiMuc** [concourse/git-resource#301]
Hi,

I'm missing the options for dealing with submodules.

On 'in' (clone) there are submodule handling parameters

I need these also to exist on 'out' (push), as the latter also does clone the repo for pushing.

At least I'd need the out Parameter: `submodules `: Optional. If `none`, submodules will neither be fetched, nor be pushed.

...or am I missing something on how to push a git repo without its submodules???

**Comment by taylorsilva** [comment]
You can set `git_config` in the `source` field of the resource with [`push.recurseSubmodules no`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushrecurseSubmodules).

```yaml
resources:
- name: repo
  type: git
  source:
    # omitting other configs
    git_config:
      - name: "push.recurseSubmodules"
        value: "no"
```
