### ISSUE TITLE
Don't push all tags, just the one specified.

### ISSUE THREAD

**Issue by willhughes-au** [concourse/git-resource#302]
In a pipeline with: 

```
      - put: git-repo
        params:
          repository: git-repo
          tag: git-tag/tag.txt 
          tag_only: true 
```

[You use the following command](https://github.com/concourse/git-resource/blob/f0d57ba2b7d43eb37dd001e14fe8bbb874b9a49a/assets/out#L105-L107): 

```
push_tags() {
  git push --tags push-target $forceflag
}
```

Which can result in trying to push all tags, and also push branches. 

Instead you should push just the specific tag. 
For example: 

```
push_tags() {
  git push push-target $tag_name $forceflag
}
```
