### ISSUE TITLE
Previous version?

### ISSUE THREAD

**Issue by rubenv** [concourse/git-resource#303]
Is there any way to figure out not just the current ref, but also the previous one?

I'd like to construct a range like this: `c82ecda..37d4ad7`

**Comment by talset** [comment]
Currently there is no option to the git resource to get the n-1 commit.
So I would suggest to use git resource to get the latest commit and define a custom task to generate your range like:

```
- name: job_range
  plan:
  - do:
    - get: git-code
      trigger: true

    - task: get-range
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: /bin/sh
          args:
          - -c
          - -e
          - |
              cd git-code
              echo $(git log -2 --format=%h) | sed 's/ /../' | tee -a /tmp/range
        inputs:
        - name: git-code
```

Your task need to use a docker image with at least git installed
