### ISSUE TITLE
Constantly showing different tags sometimes 

### ISSUE THREAD

**Issue by Bluesboy** [concourse/git-resource#312]
I have task that pulls repo and checking tags there, however sometimes it doesn't shows some tags and thus I can't be sure that I have proper version. Here is resource
```
resources:
  - name: source-code
    type: git 
    icon: github-circle
    webhook_token: ((webhook-token))
    check_every: 4h
    source:
      uri: ((git.ssh-remote))
      private_key: ((git.private-key))
      branch: master
jobs:
  - name: build-pr-image
    serial: true
    plan:
      - get: source-code
        trigger: false

      - task: semver
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: bluesboy/semver
              tag: 3.0.0
          inputs:
          - name: source-code
          outputs:
          - name: version
          run:
            path: bash
            args:
            - -exc
            - |
              export VERSION=$(semver bump patch $(git -C source-code describe --tags --abbrev=0))-c$(git -C source-code rev-parse --short HEAD)
              echo ${VERSION} > version/version
```
I'm using https://github.com/fsaintjacques/semver-tool packed in Docker Image, to bump version (but I'm sure that is irrelevant)
It looks like that sometimes resource doesn't pull latest resource version

**Comment by talset** [comment]
The resource actually clone (or fetch) the repo without `--tags flags`. It only get all tags when using tag_filter.

https://github.com/concourse/git-resource/blob/master/assets/check#L39-L59

If you want tags information without using tag_filter, we might need to implement a new parameter to force tags fetch.

**Comment by talset** [comment]
Could you try the `fetch_tags: true` option ? (https://github.com/concourse/git-resource#parameters)

I just builded a new images from git-resource master

```
resource_types:
  - name: git
    type: docker-image
    source:
      repository: cycloid/concourse-git-resource
      tag: latest
```

Let us know if solve your issue
