### ISSUE TITLE
Git branch is ignored while using commit message "include" filter

### ISSUE THREAD

**Issue by vadvks** [concourse/git-resource#313]
This resource triggers a job not only when a commit with */fix/* message appears directly in "master" branch, but also when I merge another branch to "master" that had a commit with such a message. 

```
- name: patch-master
  type: git
  check_every: 20s
  source:
    uri: ((repository))
    private_key: ((wmuser_key))
    username: wmuser
    branch: master
    commit_filter:
      include: ["/fix/"]
```

This is unexpected behaviour, as I want my job triggered only by a commit in the master branch. Please help if this is the expected behaviour
