### ISSUE TITLE
Get the latest commit of the repo always

### ISSUE THREAD

**Issue by sskmail14** [concourse/git-resource#319]
I have multiple repo to be referred in a pipeline.

Out of which one is the repo that has the configs of CI files, as part of the pipeline I would like to get the latest commit of the CI files always.

So in brief:
I would like to get the latest commit of the repo always whenever the new build is triggered in concourse. `trigger:true` is not intended since the trigger should happen via another repo.

**Comment by YoussB** [comment]
Hey @sskmail14,
thanks for waiting until I came back to this issue.
I am not really sure I understand the use case needed here.
from my basic understanding, you want to configure 2 resources with one using `trigger: true` and make sure the other is getting the latest version?

**Comment by YoussB** [comment]
Also, I want to point out that, it is way easier to get help on Discord, there are a lot of folks from the Concourse team, and the community ready to help with your setup. We are happy to discuss problems with resources and feature requests here.

**Comment by sskmail14** [comment]
Thanks @YoussB .

Am having two resource

1. Git-Resource-1
2. Git-Resource-2

Where the build will get triggered once I make any changes as part of `Git-Resource-1` but I always want `Git-Resource-2` to get the latest commit.

My concern here is if I set the `trigger:true` the pipeline gets triggered for commit that am making out of that repo. I didn't want the pipeline to get it triggered for that repo change, but it has to pick the latest commit of that branch whenever a build is getting triggered.

Note: Am using webhook from git to trigger the pipelines.

**Comment by taylorsilva** [comment]
I'm assuming this pipeline setup:

```yaml
resources:
- name: git-1
  type: git
  source: # omitted

- name: git-2
  type: git
  source: # omitted

jobs:
- name: my-job
  plan:
    - in_parallel:
      - get: git-1
        trigger: true
      - get: git-2
```

And you want to ensure that `git-2` is always gets the latest commit even though it's NOT a trigger for the job.

The best way to guarantee this is to set `check_every` on the `git-2` resource to a short interval. The con with this is that you'll be hammering your git server a lot.

Starting in v8.2.0 of Concourse (releasing soon at the time of writing) we've adjusted when checks are run, so this hammering wouldn't happen in this case.

So if you're on >= v8.2.0 of Concourse, you can set `check_every` to something short like `10s` (or any interval that's shorter than `git-1`'s check interval) which will guarantee that whenever `git-1` triggers the job, `git-2` will also be checked for the latest commit.

```yaml
resources:
- name: git-1
  type: git
  source: # omitted

- name: git-2
  type: git
  check_every: 10s #interval shorter than git-1
  source: # omitted

jobs:
- name: my-job
  plan:
    - in_parallel:
      - get: git-1
        trigger: true
      - get: git-2
```

Closing because not an issue with the resource, just a support question.
