### ISSUE TITLE
checkout a ref defined in a build step

### ISSUE THREAD

**Issue by lnhrdt** [concourse/git-resource#328]
I would like to checkout a ref that is determined in a build step. My thought was to pass the ref as a file to the resource. I did something like this:

```yaml
- get: deployment-source
  version:
    ref: build/commit
```

where `build/commit` is a file containing a sha. But the resource failed, trying to use the literal string `build/commit` as a ref.

Is what I'm trying to do possible?
