### ISSUE TITLE
Host key verification failed. fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by Roadmaster** [concourse/git-resource#331]
This is very similar to #200, that one was resolved by using "pivnet" (I don't know what that is!) back in 2018. However, I'm seeing this on my Concourse 6.5.1 install when setting up my first publishing pipeline and wanted to ask how this is typically resolved.

```
selected worker: concourse

Host key verification failed.

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.
```

My resource config is like so:
```
  - name: resource-some-landing-branch
    type: git
    source:
      uri: git+ssh://roadmr@git.someplace.com/some/path/components
      branch: landing
      private-key: ((landing-job-private-key))
```

I get the error when trying to `put` using the git resource with a `git+ssh` URI (it's a privately-hosted repo, not github). On our existing Jenkins instance we solve this by ensuring the host keys exist in the box we're trying to do git operations from, either by putting a known key in .ssh/known_hosts, or by doing `ssh -o StrictHostKeyChecking=no the.git.host.example.com` (which causes SSH to connect and fetch the keys, thus they are available when git wants to use the SSH transport). But I haven't figured out how to do this with the concourse git resource.

Something like being able to specify the [SSH command for git](https://stackoverflow.com/questions/7772190/passing-ssh-options-to-git-clone) might help in this case, but I couldn't find any obvious way to configure this in the resource.

Or maybe a way to inject known host keys as part of the resource config would also work and might be less iffy than just disabling host key checking via options.

How are people solving this problem?

Thanks in advance for any advice!

- Daniel

**Comment by Roadmaster** [comment]
Apologies for not reading the documentation carefully. I was able to solve this by:

```
source:
   git_config:
   - name: core.sshCommand
     value: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  (other options)
```
I'll close this issue now, sorry!

- Daniel
