### ISSUE TITLE
How to trigger job when submodule update?

### ISSUE THREAD

**Issue by huangyisan** [concourse/git-resource#336]
I have two repositories A and B, and the B is a submodule of A.

I want to trigger a job to get repository A with the latest submodule B, when the submodule B has a new update, even though there is no change in A.

Could you tell me is there any way to solve it?
Thanks!

**Comment by taylorsilva** [comment]
For future readers, questions like this should go under: https://github.com/orgs/concourse/discussions/categories/help-support

I realize OP has probably moved on from this issue. Responding and closing this issue now for future readers.

---

I would create two instances of the git resource in your pipeline, one for each repo, A and B.

```yaml
resources:
- name: repo-a
  type: git
  source: # omitting config

- name: repo-b
  type: git
  source: # omitting config
```

Then in your job that you want to trigger, I would do this:

```yaml
jobs:
- name: my-job
  plan:
    - in_parallel:
      - get: repo-a
      - get: repo-b
        trigger: true
```

That will trigger `my-job` whenever a new commit is pushed to `repo-b`. You can follow up the get steps with a `task` step that updates `repo-a` with the latest commit from `repo-b`.

```yaml
platform: linux

inputs:
- name: repo-a
- name: repo-b

outputs:
- name: repo-a

run:
  path: some/script/to/update/submodule.sh
```
