### ISSUE TITLE
Pinning to old commit shas does not work as documented

### ISSUE THREAD

**Issue by XanderStrike** [concourse/git-resource#337]
## Context

I have the following resource defined

```
- name: cf-for-k8s
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((github_private_key.private_key))
    branch: develop
  version:
    ref: 3ac710676c7fca595765518d0882af011e955d37
```

The pipeline shows the pinning happening:

![image](https://user-images.githubusercontent.com/1565303/96499822-c6d4c700-1202-11eb-9536-be210d0120be.png)

Checking the resource does not report any errors, even when specifying the sha:

![image](https://user-images.githubusercontent.com/1565303/96499994-08fe0880-1203-11eb-8fb7-efc68b072bb8.png)

[The commit definitely exists](https://github.com/cloudfoundry/cf-for-k8s/commit/3ac710676c7fca595765518d0882af011e955d37) and I can check it out locally.

## Observed

When the pipeline is run, it hangs forever on `pinned version not found`:

![image](https://user-images.githubusercontent.com/1565303/96500115-3c409780-1203-11eb-847b-08112d4b501c.png)

## Expected

I would expect the pipeline to run, and pull the version of cf-for-k8s specified.

### Workaround

For now, creating a new branch at that commit and using that branch has let me move forward with what I'm working on, but it would be more convenient to be able to pin at an arbitrary git sha without having to modify the github repo. In cases where users don't have permission to create branches on resource repos this would not be an option.
