### ISSUE TITLE
Maybe a bug with tag_regex? Resource versions created with both SHA1 and tag

### ISSUE THREAD

**Issue by ankeesler** [concourse/git-resource#353]
**What happened?**

- With this resource:
```yaml
  - name: mirrors_github_pinniped
    type: git
    icon: github
    tags: [ pinniped-ci-calatrava ]
    source:
      uri: git@gitlab.whatever.com:akeesler/fake-mirrors_github_pinniped.git
      tag_regex: v[0-9]+\.[0-9]+\.[0-9]+ # e.g., v0.4.1
      private_key: REDACTED
```

- I see these resource versions:
![image](https://user-images.githubusercontent.com/3081590/110514206-109c4c00-80d5-11eb-8254-bef6fa90162b.png)

- Because of this, the next `vx.y.z` tags that I pushed to the repo did not show up as a resource version because the latest resource version has a `ref` of a SHA1 which filtered out all tags at this line: https://github.com/concourse/git-resource/blob/30c1e237dd9f919c71230501c771b4188383b51d/assets/check#L161.

**What did I expect to happen?**

- I hoped to see only resource versions with a `ref` matching my `tag_regex`.

**Notes**

- I am working with Concourse 7.0.0 at https://hush-house.pivotal.io.
