### ISSUE TITLE
Add .git/branch as additional populated file

### ISSUE THREAD

**Issue by jmatsushita** [concourse/git-resource#356]
Would you consider adding a `.git/branch` file in the additionally populated files with the branch name? Unless I'm missing something I can't see how to transform the branch name that triggered the pipeline into a variable for instantiated pipelines.

This would be nice to make use of the instanced pipeline experimental feature and use `set_pipeline` with the branch value in this way:
```
- name: configure-pipelines
  public: true
  plan:
    - get: my-repo
      trigger: true

    - load_var: branch_name
      file: .git/branch

    - set_pipeline: build
      file: my-repo/.concourse.yml
      instance_vars:
        branch: ((.:branch_name))
``` 

The implementation could be
```
git symbolic-ref -q --short HEAD > .git/branch
```
