### ISSUE TITLE
gitnotes support for pusing

### ISSUE THREAD

**Issue by pratikbalar** [concourse/git-resource#362]
- need gitnotes support for pushing only
ref:
  - https://itnext.io/git-notes-your-ci-process-46b2fd5ac52

**Comment by pratikbalar** [comment]
Ahh, got it. Question can I only add notes without anything else!
https://github.com/concourse/git-resource/blob/891c32f1b4b43beca81adff0890b8fea35bcbc0b/assets/out#L113-L118

**Comment by pratikbalar** [comment]
Yes I can, Tested
> Ahh, got it. Question can I only add notes without anything else!

But can I add git notes to a particular commit?
Apparently I found that I need to save change log in git-notes with some other logs and attach that to a particular commit (if possible) or to a last commit.

> ref https://itnext.io/git-notes-your-ci-process-46b2fd5ac52

```
- get master
---
- task: add-git-notes
---
- put: master
  params:
    repository: master
    notes: master/notes

```
