### ISSUE TITLE
Allow pushing branches with dynamically generated names

### ISSUE THREAD

**Issue by akshaymankar** [concourse/git-resource#376]
If someone wants to specify a branch override in the `out` params, they have to decide the name of the branch while writing the pipeline. Would it be possible to source this name from a file and consume this as `branch_file` in out params?

**Comment by taylorsilva** [comment]
You can use the `load_var` step to read a branch name from a file and then reference it in the params of your put step.

`load_var` docs: https://concourse-ci.org/load-var-step.html

Quick example of what the relevant steps might look like:

```yaml
# pretend there's a prior step that creates an output
# called "branch" with a file called "name" inside it
# that contains the branch name to put to
- load_var: branch
  file: branch/name
- put: repo
  params:
    branch: ((.:branch))
```
