### ISSUE TITLE
git-config no way to set multivalues

### ISSUE THREAD

**Issue by nosdod** [concourse/git-resource#383]
I have an environment where, to access git repos, I need to specify two http.extraHeader values. If I provide them to a git resource as
```
 git_config:
   - name: http.extraHeader
     value: test
   - name: http.extraHeader
     value: test2
```
the second configuration overwrites the first, rather than adding it as a second configuration.

What I see in /root/.gitconfig is
```
[http]
        extraHeader = test2
```
What I expect to see is
```
[http]
        extraHeader = test
        extraHeader = test2
```
git-resource needs to somehow recognise the second configuration as an attempt to set a multi-value and add the --add option to the git config command it runs.
