### ISSUE TITLE
Changes outside of the specified Paths are triggering pipelines

### ISSUE THREAD

**Issue by bajunkins** [concourse/git-resource#384]
Hi, I have two different git resources pointing to the same repository; one of them has a paths option pointing to a specific subdirectory. I'm finding that even changes outside of this subdirectory are triggering the job to run.

Here are the resources: 

```
- name: master-git
  type: git
  icon: git
  source:
    branch: ((default-branch))
    uri: ((gitlab-url))/((gitlab-project)).git
    username: ((gitlab-username))
    password: ((gitlab-token))
  
- name: subdirectory-git
  type: git
  icon: git
  source:
    uri: ((gitlab-url))/((gitlab-project)).git
    username: ((gitlab-username))
    password: ((gitlab-token))
    branch: ((default-branch))
    paths:
      - subdirectory/**
```

For the paths options, I've tried several different approaches:  - subdirectory/**,  - subdirectory/*,  - subdirectory

Here is the relevant part of the job:

```
- name: subdirectory-job
  serial: true
  plan:
    - get: master-git
    - get: subdirectory-git
      trigger: true 
```

This job is triggering from changes anywhere in the repo. I only want it to trigger for files under subdirectory/. Is this expected behavior? If so, how can I achieve what I'm looking for
