### ISSUE TITLE
Support blob/regex pattern for branch names

### ISSUE THREAD

**Issue by markdboyd** [concourse/git-resource#398]
### Is your feature request related to a problem? Please describe.

I would like to use the [Github merge queue feature](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) to manage Dependabot PRs, among other things. But in order to have Concourse CI jobs triggered by the merge queue builds, [I need to be able to match against PRs by a blob/regex pattern: `gh-readonly-queue/{base_branch}/`](https://github.com/orgs/community/discussions/46757). 

From what I can tell from the documentation and perusing the `check` script code, the `branch` option currently only supports a static branch name. 

### Describe the solution you'd like

I'd like to add a name option for check, `branch_pattern`, to support dynamically matching against branch names by a blob pattern

Then it could be used like so when declaring a resource in a pipeline:

```yaml
- name: merge-queue-builds
  type: git
  source:
    uri: https://github.com/concourse/git-resource
    branch_pattern: gh-readonly-queue/main/*
```

And then CI jobs in the pipeline could be triggered by this resource.
