### ISSUE TITLE
detected dubious ownership in repository at '/tmp/build/get'

### ISSUE THREAD

**Issue by NullOranje** [concourse/git-resource#404]
### Describe the bug

When attempting to get a `git-resource`, we receive the git error `detected dubious ownership` instead of pulling the source code.

### Reproduction steps

1. Deploy concourse quickstart using provided docker-compose.yml (using Concourse 7.9.1)

2. Deploy a simple pipeline: 

```yaml
resources:
  - name: git-repo
    type: git
    icon: git
    source:
      uri: http://gitea:3000/org1/myproject
      username: ((gitea.username))
      password: ((gitea.password))
jobs:
- name: validate-repo
  plan:
    - get: git-repo
      trigger: false
    - task: list-files
      config:
        inputs:
          - name: git-repo
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: busybox
        run:
          path: tree
```
3. Unpause the pipeline
4. Receive the following error:
```
selected worker: 31354ca107d3
Cloning into '/tmp/build/get'...
fatal: detected dubious ownership in repository at '/tmp/build/get'
To add an exception for this directory, call:

	git config --global --add safe.directory /tmp/build/get

```
...

### Expected behavior

Expect the git repo to be available for pipeline consumption,

**Comment by NullOranje** [comment]
This seems to be an issue with houdini/Docker for Mac.  Running this on a Kubernetes cluster on the same Docker for Mac instance with containerd does not encounter this issue.

**Comment by dschila** [comment]
Alternative workaround if you work on a local concourse instance:
```yaml
git_config:
- name: safe.directory
  value: /tmp/build/get
```

**Comment by ismail-temiz** [comment]
> Alternative workaround if you work on a local concourse instance:
> 
> ```yaml
> git_config:
> - name: safe.directory
>   value: /tmp/build/get
> ``` 

This has worked for me on the `get` step but having the same issue now in the `put` step as
```
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
fatal: detected dubious ownership in repository at '/tmp/build/put/repo'
To add an exception for this directory, call:

	git config --global --add safe.directory /tmp/build/put/repo
```

**Comment by ismail-temiz** [comment]
```
    git_config:
    - name: safe.directory
      value: '*'
```

Solved the issues for me

**Comment by reshmiasish** [comment]
this didnt solve issue for me :(

**Comment by pm3ndoza** [comment]
> ```
>     git_config:
>     - name: safe.directory
>       value: '*'
> ```
> 
> Solved the issues for me

Question, where do you writ that, because, i tried on the task, on the resource section, and not be able to works

**Comment by ismail-temiz** [comment]
> > ```
> >     git_config:
> >     - name: safe.directory
> >       value: '*'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Solved the issues for me
> 
> Question, where do you writ that, because, i tried on the task, on the resource section, and not be able to works
> 
> Even I try this. but still failing
> 
> ```
> resources:
> - name: concourse-examples
>   type: git
>   icon: github
>   check_every: 30m
>   source:
>     uri: https://github.com/concourse/examples
>     branch: master
>     safe_directory: /tmp/build/*
> ```

Like this
```
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/foo.git
    # this is to avoid git permission error.
    git_config:
    - name: safe.directory
      value: '*'
```

**Comment by pm3ndoza** [comment]
> > > ```
> > >     git_config:
> > >     - name: safe.directory
> > >       value: '*'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Solved the issues for me
> > 
> > 
> > Question, where do you writ that, because, i tried on the task, on the resource section, and not be able to works
> > Even I try this. but still failing
> > ```
> > resources:
> > - name: concourse-examples
> >   type: git
> >   icon: github
> >   check_every: 30m
> >   source:
> >     uri: https://github.com/concourse/examples
> >     branch: master
> >     safe_directory: /tmp/build/*
> > ```
> 
> Like this
> 
> ```
> resources:
> - name: repo
>   type: git
>   source:
>     uri: https://github.com/foo.git
>     # this is to avoid git permission error.
>     git_config:
>     - name: safe.directory
>       value: '*'
> ```

Have the same issue, i can not be able to get the repo, because I don't know where i can put those lines.

**Comment by ismail-temiz** [comment]
@pm3ndoza not sure what you mean. I show where you need to put those lines in the example above.

**Comment by jamie-pate** [comment]
FYI this is not just an ARM/mac/Houdini problem, I'm facing it on my amd64 vm using containerd

The workaround posted above works for me, so it's NBD i think

```
CONCOURSE_WORK_DIR=/mnt/concourse-worker/worker
CONCOURSE_LOG_LEVEL=error
CONCOURSE_TSA_HOST=<host>:2222
CONCOURSE_TSA_PUBLIC_KEY=/mnt/concourse-worker/keys/tsa_host_key.pub
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/mnt/concourse-worker/keys/worker_key

CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=error
CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0
CONCOURSE_BAGGAGECLAIM_DRIVER=btrfs

CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=1

CONCOURSE_RUNTIME=containerd
```

**Comment by jamie-pate** [comment]
This is the pipeline that had issues for me (obfuscated a bit)

```
resource_types:
- name: sharepoint-folder
  type: registry-image
  source:
    username: ((registry.username))
    password: ((registry.password))
    repository: cr.local/sharepoint-folder-resource
- name: git-gerrit
  type: registry-image
  source:
    username: ((registry.username))
    password: ((registry.password))
    # this is https://github.com/jamie-pate/git-resource 39 commits behind concourse/git-resource:master.
    # none of those 39 commits are related afaict
    repository: cr.local/git-resource 
- name: psirt-data-api
  type: registry-image
  source:
    username: ((registry.username))
    password: ((registry.password))
    # handles some local REST api calls
    repository: cr.local/psirt-data-resource
resources:
- name: sp-outbreak
  type: sharepoint-folder
  source:
    site_url: https://mycorp.sharepoint.com/sites/((site_name))
    client_id: ((fdn-outbreak-poll.clientId))
    client_secret: ((fdn-outbreak-poll.clientSecret))
    folder_path: ((folder_path))
    pattern: '*.json'
    single: true
    filter_json_path: '/[*]/status[@.match(/\bFOS\b|^ALL$/)]'
- name: sr-packages
  type: git-gerrit
  source: &sr-packages-source
    uri: ssh://gerrit.local:29418/fdn-publish
    branch: ((publish_branch))
    private_key: ((gerrit.private_key))
    private_key_user: ((gerrit.username))
    private_key_passphrase: ((gerrit.private_key_passphrase))
    git_config:
    - name: user.name
      value: ConcourseFosexp
    - name: user.email
      value: ((gerrit.username))@mycorp.com
- name: refs-for-sr-packages
  type: git-gerrit
  source:
    <<: *sr-packages-source
    # needs to be here because the get params aren't sent when you 'get' after 'put'
    loose_refs: true
    git_config:
      - name: safe.directory
        value: '*'
- name: fdn-publish
  type: git
  source:
    uri: ssh://gerrit.local:29418/fdn-publish
    branch: ((branch))
    private_key: ((gerrit.private_key))
    private_key_user: ((gerrit.username))
    private_key_passphrase: ((gerrit.private_key_passphrase))
- name: fortipkg
  type: git
  source:
    uri: ssh://gerrit.local:29418/fortipkg
    branch: main
    private_key: ((gerrit.private_key))
    private_key_user: ((gerrit.username))
    private_key_passphrase: ((gerrit.private_key_passphrase))
# PSIRT data for products..
- name: psirt-data-#...
# ... 15 api call resources skipped
jobs:
- name: poll
  serial: true
  plan:
  - get: sp-outbreak
    version: every
    trigger: true
    params:
      fetch_all: true
  - get: fortipkg
  - task: fortipkg-make
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          username: ((registry.username))
          password: ((registry.password))
          repository: cr.local/fortidev-build-essential
          tag: latest
      run:
        dir: fortipkg
        path: /bin/bash
        args:
        - -ceux
        - |
          make fdspacker FORTIDEV_VERSION_MAJOR=6
          cp pkg/mycorp/fdspacker-*/bin/host/* bin
          [ -x bin/pkgpacker ]
          [ -x bin/objpacker ]
      inputs:
      - name: fortipkg
      outputs:
      - name: fortipkg
  - get: sr-packages
# PSIRT data for products:fortios, fortianalyzer, fortimanager, fortiap, fortiswitch, fortimail
  - in_parallel:
    - get: psirt-data-x
      version: every
      trigger: true
    - get: psirt-data-y
      version: every
      trigger: true
    - get: psirt-data-z
      version: every
      trigger: true
    #  ... etc
# a task to put all psirt data files into one directory
  - task: merge-psirt-files
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: node
          tag: ((node_version))-bullseye
      run:
        path: /bin/bash
        args:
        - -ceux
        - |
          cp -a psirt-data-x/. api-psirt/
          cp -a psirt-data-y/. api-psirt/
          cp -a psirt-data-z/. api-psirt/
          # ...
      inputs:
      - name: psirt-data-x
      - name: psirt-data-y
      - name: psirt-data-z
      # ...
      outputs:
      - name: api-psirt
  - get: fdn-publish
  - try:
      task: pkg
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: node
            tag: ((node_version))-bullseye
        run:
          path: fdn-publish/pipelines/fdn-package-pkg.sh
          args:
          - fdn-publish
          - sp-outbreak
          - sr-packages
          - api-psirt
          - fortipkg
          - ((publish_branch))
          - ((firmware_version))
        inputs:
        - name: fdn-publish
        - name: sr-packages
        - name: sp-outbreak
        - name: fortipkg
        - name: api-psirt
        outputs:
        - name: sr-packages
      on_success:
        put: refs-for-sr-packages
        params:
          repository: sr-packages
          refs_prefix: refs/for

```

fdn-package-pkg.sh
```
#!/bin/bash
set -eux

# filename and script locations
root_dir=$(pwd)
fdn_publish=$1
sp_outbreak=$2
sr_packages=$3
#...
cd $sr_packages
git add -A json
# check if any staged change in json directory
staged_changes=$(git diff-index --name-only HEAD json)
if [[ -z "$staged_changes" ]]; then
  echo "Skip packaging since no new useful changes detected in the json directory."
  exit 1
else
  echo "staged useful changes in json directory detected. Now start packaging..."
fi

cd $root_dir

# create a tar with all the json files
ln -s $sp_outbreak outbreak
ln -s $api_psirt psirt
# Add outbreak/psirt directories and add version.json at the top of the archive.
# --directory is used to specify ver_file_name's directory so its parent directory structure is not kept.
# The order matters, so add new files before --directory.
tar --dereference -cvf $tar outbreak/* $includepsirt --directory=$sr_packages $ver_file_name

# 'package' the tar file
mkobjpkg $tar $obj $kg

ls -lh $obj $tar $pkg

# ensure we actually created a package file
[ -f $pkg ]

find $json_path -type d -exec ls -lh {} +

# Create a Change-Id like the gerrit git-commit hook, except it's not random.
change_id=$( echo "branch=$publish_branch" | cat - $ver_file | git hash-object --stdin )
echo "$publish_branch" | sed 's|fos-fdn-sr-packages-||' >> bump.txt
echo "" >> bump.txt
echo "Change-Id: I${change_id}" >> bump.txt

mv $tar $sr_packages/
# Create a new commit
cd $sr_packages
# stage all changes (new, modified, removed) again
git add -A

git config user.name ConcourseMyCorp
git config user.email noreply@concourse.local

git commit -F ../bump.txt



```

relevant git details about 'dubious ownership'

https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9

**Comment by jamie-pate** [comment]
🤔 here are the ownership details in the task that was failing

```
/tmp/build/4ff15b93# ls -lhd /tmp
drwxrwxrwt 1 999 999 62 Apr 30 18:34 /tmp

/tmp/build/4ff15b93# ls -lh
drwxr-xr-x 1  999  999  228 Apr 30 18:33 fortipkg
drwxr-xr-x 1 root root  112 Apr 30 18:34 sr-packages
```

**Comment by taylorsilva** [comment]
From https://github.com/concourse/concourse/releases/tag/v7.9.0 ("Bundled Resource Types" section) 7.9.0 came with [v1.14.6](https://github.com/concourse/git-resource/releases/tag/v1.14.6) of the git resource.
Looking at the diff between that version and the latest: https://github.com/concourse/git-resource/compare/v1.14.6...v1.18.3

So I don't think upgrading will fix anything for you. You can always trying using the latest version of the git resource by adding this to your pipeline:

```yaml
resource_types:
- name: git
  type: registry-image
  source:
    repository: docker.io/concourse/git-resource
    tag: "1.18.3"
```

That will override the `git` resource on the worker for whichever pipeline you add this to.

---

Your reproducible still has a lot of noise in it that I need to sift through. I'm hoping for something more succinct and portable, like what I illustrated here:

```yaml
resources:
- name: repo
  type: git
  source:
    uri: https://gitea.com/gitea/docs.git

jobs:
- name: get-repo
  plan:
    - get: repo
```

From looking at your pipeline, specifically the configuration of the `refs-for-sr-packages` resource where I see you have the `safe.directory` workaround setup, you have the following params set for that resource:

- `loose_refs: true` - which I don't think is a thing at all for the resource, so probably a no-op setting
- `uri: ssh://gerrit.local:29418/fdn-publish` and you're using ssh instead of http. OP was using http
- `branch`, `private_key`, `private_key_user`, `private_key_passphrase` - none of these were specified by OP

Based on all this info the only patterns I'm seeing so far are:

- Git repo is on a non-Github platform. I highly doubt this would be the cause of the issue though.
- The URI's both don't end in `.git`

I just noticed my example used an HTTP URI that ended in `.git`. But both you and OP used URI's that did not end in `.git`, though you are using different protocols. Let's try my pipeline but with the URI not ending with `.git`. I would expect this to work. When I locally do `git clone https://gitea.com/gitea/docs` the repo clones without issue.

```yaml
resources:
- name: repo
  type: git
  source:
    uri: https://gitea.com/gitea/docs

jobs:
- name: get-repo
  plan:
    - get: repo
```

And it still worked:
```
started test/get-repo #1

selected worker: 375543d77161
Cloning into '/tmp/build/get'...
e1500d2 Optimize the 404 page (#216)
succeeded
```

I repeated this test using v7.9.0 of Concourse since you mentioned using it. The job completed successfully, no error.

This is on a linux/amd64 machine doing docker compose with https://github.com/concourse/docs/blob/master/docker-compose.yml which is what OP claimed to use.

As this stands, it's still unclear what is causing this error or how to even reproduce it. Like OP experienced, it seems like it might be an issue with the configuration on the worker. Without a reproducible I can't investigate this any further.
