### ISSUE TITLE
commit_filter not work

### ISSUE THREAD

**Issue by sikateweiqi** [concourse/git-resource#407]
### Is your feature request related to a problem? Please describe.

I write the resources as below:

```
  - name: bitbucket-repo
    type: git
    icon: bitbucket
    source:
      uri: xxxxxxxxxx
      private_key: |
        ((ci.bitbucket_private_key))
      branch: test
      paths:
        - file
      commit_filter:
        exclude:
          - author: "bot"
```

But the exclude condition doesn't work, the resources still be trigger by the author "bot".

### Describe the solution you'd like

Can you help give the more detail example about commit_filter?
The configuration is very important.
