### ISSUE TITLE
Cannot fetch/checkout specific version with no branch

### ISSUE THREAD

**Issue by gsaslis** [concourse/git-resource#415]
### Describe the bug

- I am trying to use the git resource to fetch a specific commit from a repository. 
- The commit exists on the repository. 
- The commit is not on a specific branch.
- git-resource cannot find this `version.ref`.

### Reproduction steps

1. Start up concourse (7.9.1)
2. Define pipeline

```yaml
---
---
resources:
- icon: git
  name: repo
  source:
    uri: "https://radicle.yorgos.net.gr/z4QJ2XjzjTioTfuWkR2J2rJjeL9dg.git"
  type: git

jobs:
- name: configure-pipeline
  plan:
  - get: "repo"
    params:
      fetch: ["48bb15c1ed6f085c0ee0b3f813a991cedd195f2b", "4c4a3907f9e13018f7899b4ae98d92782fa5ab44"]
    version:
      ref: 4c4a3907f9e13018f7899b4ae98d92782fa5ab44

  - file: "repo/.concourse/config.yaml"
    set_pipeline: self
    vars:
      patch_head: 4c4a3907f9e13018f7899b4ae98d92782fa5ab44
```
3. Create and trigger pipeline in concourse

```bash
fly -t tutorial set-pipeline -p repo-configure -c pipeline.yaml
fly -t tutorial unpause-pipeline -p config
fly -t tutorial trigger-job --job config/configure-pipeline --watch
```

5. Job gets stuck on: 

```
preparing build
checking pipeline is not paused
checking job is not paused
discovering any new versions of repo
waiting for a suitable set of input versions
repo - pinned version ref:4c4a3907f9e13018f7899b4ae98d92782fa5ab44 not found
checking max-in-flight is not reached
```

### Expected behavior

I should be able to fetch/checkout specific commits, even when they are not on a branch. 

Here is the commit https://app.radicle.xyz/nodes/radicle.yorgos.net.gr/rad:z4QJ2XjzjTioTfuWkR2J2rJjeL9dg/commits/4c4a3907f9e13018f7899b4ae98d92782fa5ab44

Here is how I can clone the repo and checkout the specific commit with git tooling: 

```bash
git clone https://radicle.yorgos.net.gr/z4QJ2XjzjTioTfuWkR2J2rJjeL9dg.git test-my-ci
cd test-my-ci
git fetch origin 48bb15c1ed6f085c0ee0b3f813a991cedd195f2b
git fetch origin 4c4a3907f9e13018f7899b4ae98d92782fa5ab44
git checkout FETCH_HEAD
```

### Additional context

I tried various permutations of this: 
-  defining `version.ref` on the resource / on the get step
- adding `params.fetch` on the get step (which seems to be supported by the `in` script)
- using the commit hash as the `branch`

... with no luck. 

If it sounds like this scenario should be supported and that there should be some combination that supports this, I would really appreciate some pointers! 

Thanks in advance!!

Relevant references I found: 
- https://github.com/concourse/git-resource/issues/337
- https://github.com/concourse/git-resource/commit/6c37f57b60f5fe841ddda76de0cc04b1afc9997d (unfortunately this example uses `branch`
