### ISSUE TITLE
Old, out of order Docker hub tag (2.7.0) breaks CI depending on semver

### ISSUE THREAD

**Issue by marco-m-pix4d** [concourse/git-resource#429]
### Describe the bug

Hello,

consider

```
  - name: git-resource
    type: registry-image
    source:
      repository: concourse/git-resource
```

This configuration, since it lacks `tags` and `tag_regex`, according to [registry-image check step](https://github.com/concourse/registry-image-resource?tab=readme-ov-file#check-step-check-script-without-tag-or-tag_regex-discover-semver-tags), will detect all tags that are semver-like and return the "latest" of such tags.

My intent was thus to pickup the current latest tag in the git repo, which is [v1.16.0](https://github.com/concourse/git-resource/tags).

Unfortunately, the Docker Hub registry for the git resource image has an old (7 years ago) wrong tag of [2.7.0](https://hub.docker.com/layers/concourse/git-resource/2.7.0/images/sha256-14542abafcbe5de4faa403fb472a3dae2a0d6e4d3ac735c580a3957cdc162c85?context=explore)

This has the effect that , since `2.7.0` is greater than `1.16.0`, the pipeline always picks up the old, wrong tag `2.7.0`.

![versions](https://github.com/user-attachments/assets/cb5756ee-6788-4653-906f-ee0c1ff892e4)

Now, I think I might be able to work around this with the `semver_constraint` setting of the registry-image (haven't checked yet), but I think we should just delete this tag from Docker hub.

@xtremerui @taylorsilva would you be so kind to have a look?

Thanks a lot, greatly appreciated :cat

### Reproduction steps

Use 
```
  - name: git-resource
    type: registry-image
    source:
      repository: concourse/git-resource
```

### Expected behavior

Latest reported version to be `1.16.0`, while it is `2.7.0`.
