### ISSUE TITLE
When using tag_filter, the version reported by 'in' should be the tag name

### ISSUE THREAD

**Issue by keymon** [concourse/git-resource#45]
When using `tag_filter`, the `check` command [reports the tag name instead of the hash in the version list](https://github.com/concourse/git-resource/blob/d952cdb40964b8f67e1ec023bc2907ab19dc0c88/assets/check#L56-L59)

But then the `in` command returns the [hash not the tag](https://github.com/concourse/git-resource/blob/d952cdb40964b8f67e1ec023bc2907ab19dc0c88/assets/in#L74)

I think it should report the tag if available.

**Comment by keymon** [comment]
Without this patch, a pipeline like this:

![screenshot from 2016-04-12 14 14 19](https://cloud.githubusercontent.com/assets/280032/14461086/ed70a15a-00b8-11e6-99aa-81c02ea2efbe.png)

which is triggered by tags, will use the tag as input of the first job and then the hash. The git resource will report these versions:

![screenshot from 2016-04-12 14 13 47](https://cloud.githubusercontent.com/assets/280032/14461115/163f69ea-00b9-11e6-996d-f01f1bc850ef.png)

Where first is a tag, that is input of the first job, and then a hash that is the input of the next jobs.

**Comment by tomwhoiscontrary** [comment]
I've also seen this, but only intermittently:

![image](https://cloud.githubusercontent.com/assets/539012/14463657/d6fb3696-00c3-11e6-8ac7-7e64b2414668.png)

The configuration for this resource is:

```yaml
- name: broker-release-final
  type: git
  source:
    uri: git@github.com:CLASSIFIED/TOP-SECRET.git
    branch: master
    private_key: {{private_key}}
    tag_filter: "v*"
```
