### ISSUE TITLE
Ability to Disable [ci-skip] via Source Configuration

### ISSUE THREAD

**Issue by zachgersh** [concourse/git-resource#59]
Spoke with @vito about this over the w/e:

[ci-skip] is nice but it stops anyone else from pulling those same commits in your repo. Proposing something like this to fix the problem:

```
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:concourse/git-resource.git
    branch: master
    disable_ci_skip: true
```
