### ISSUE TITLE
submodules of submodules seem to be borked in new git resource version

### ISSUE THREAD

**Issue by ryanmoran** [concourse/git-resource#64]
After cloning `cf-release` I see the following when running `git status`:
```
fatal: Not a git repository: /tmp/build/get/.git/modules/src/capi-release/modules/src/cloud_controller_ng
fatal: 'git status --porcelain' failed in submodule src/capi-release
```

Here is a pipeline that can recreate the issue on concourse v1.3.0:
```yaml
resources:
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master

jobs:
- name: check-status
  plan:
  - aggregate:
    - get: cf-release
      resource: cf-release
  - task: status
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalcfreleng/minimal
      inputs:
      - name: cf-release
      run:
        path: /usr/bin/git
        args:
        - status
        dir: cf-release
```
