### ISSUE TITLE
HTTPS auth doesn't work

### ISSUE THREAD

**Issue by chrisburrus** [concourse/git-resource#65]
Git resources using https auth don't seem to function at all.

Using this setup:

```
resources:
- name: reponame
  type: git
  source:
    uri: https://github.com/companyname/reponame.git
    branch: master
    username: githubusername
    password: githubpassword
```

The check script fails with the following error message:

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: could not read Username for 'https://github.com': No such device or address
```

HTTPS auth is important because you can't authenticate submodules using private keys. Thanks!

**Comment by chrisburrus** [comment]
As a note, it works if you pass the credentials in explicitly in the uri:

`uri: https://username:password@github.com/companyname/reponame.git`

But then the submodules fail to load, as the credentials attempt to load via ssh:

```
Submodule 'src/subrepo' (git@github.com:company/subrepo.git) registered for path 'src/subrepo
Cloning into 'src/subrepo'...
Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by vito** [comment]
@MatthiasWinzeler any thoughts on this? we've never used it ourself. does it work for you?

**Comment by MatthiasWinzeler** [comment]
the mechanism definitely works - we have tons of git resources that successfully fetch git repos from our internal gitlab using http auth.

I quickly checked, it also works fine with github. 

@chrisburrus Can you double check your password? I receive your exact error when I try with a wrong password. Makes sense, since git tries to ask the user for the correct password and can't allocate a tty (in the container).

**Comment by chrisburrus** [comment]
@MatthiasWinzeler Based on that information, I tried a fresh account, and it worked just fine. I eventually realized what the original problem was - the problem was that 2FA was set up on the account. Is there a way to use an account with 2FA and https authentication?

But past that you are correct, it otherwise works just fine.

**Comment by vito** [comment]
That makes sense then. There's no way to automate 2FA (kinda the whole point), so you should probably be using private keys instead.

**Comment by MatthiasWinzeler** [comment]
@chrisburrus : When using 2FA, you can use [Github's personal access tokens](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) instead of the password. Just tested it and it works fine.

**Comment by vito** [comment]
Ah, neat. Good to know!

**Comment by mxplusb** [comment]
Wanted to update on this issue. I have the same issue, but I don't have 2FA enabled.

This doesn't work and fails with the same error:

```yaml
- name: repo
  type: git
  source:
    uri: https://git.private.org/path/repo.git
    branch: master
    username: ((git.username)) # interpolated to <user>
    password: ((git.password)) # interpolated to <password>
```

But this does (sporadically - might just be my setup):

```yaml
- name: repo
  type: git
  source:
    uri: https://((git.username)):((git.password))@git.private.org/path/repo.git # interpolated properly
    branch: master
```

The private repository is with Gitlab, not Github, and since 2FA/SSH isn't enabled, cloning with a private key or personal token isn't allowed. The problem is if there is an error in the git resource, it will dump the credentials into the stderr of the resource:

```
stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: could not read Username for 'https://((git.username)):((git.password))@git.private.org': No such device or address
```

If you look at the [git-credential-store](https://git-scm.com/docs/git-credential-store) documentation, instead of populating `~/.netrc`, you should be able to populate `~/.git-credentials` with `https://user:pass@domain.com` to solve the problem.
