### ISSUE TITLE
 Host key verification failed

### ISSUE THREAD

**Issue by acca301** [concourse/git-resource#66]
I have just started learning Concourse CI from the tutorial https://github.com/starkandwayne/concourse-tutorial On Step 12 got into troubles with git-resource, the process fails on SSH host key verification.

This is the link to the [original issue](https://github.com/starkandwayne/concourse-tutorial/issues/51) so Dr Williams would be in the loop.

**Comment by vito** [comment]
You need to configure a `private_key` to use SSH URIs.

**Comment by acca301** [comment]
private_key does not help either.

Host key verification occurs way before the SSH client has a chance to present the key.

**Comment by vito** [comment]
Git has terrible error messages. It'll say that when really the auth failed, the repo didn't exist, or the moon was half full. I would double check the formatting of your private key. It should look like:

```yaml
resources:
- name: foo
  type: git
  source:
    uri: ...
    private_key: |
      ---BEGIN BLAH BLAH---
      .....
      ---END BLAH BLAH---
```

**Comment by acca301** [comment]
My bad. ` | ` was they key.
I usually do chomping with `|-`, thus mine was:
```yaml
  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |-
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---
```
 that was the show stopper in this case.
