### ISSUE TITLE
variables don't expand properly in uri

### ISSUE THREAD

**Issue by bacoboy** [concourse/git-resource#83]
Curly bracket expansion doesn't play nice when used as part of a URI:
```
resources:
- name: tools
  type: git
  source:
    uri: git@github.com:{{github-username}}/tools.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: test
  plan:
  - get: tools
```

After `set-pipeline` passing `--var github-username=bacoboy` expands with extra quotes:

```
      uri: git@github.com:"bacoboy"/tools.git
```

This results in a resource error:
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: remote error: 
  %s is not a valid repository name
  Email support@github.com for help
```
