### ISSUE TITLE
/out should be able to create merge commits

### ISSUE THREAD

**Issue by d** [concourse/git-resource#96]
## Background
Our team is using a simple two-branch workflow where developers would push to `develop`,  and CI would promote to `master`. Part of our promotion jobs involves a commit by CI on `develop`, and we maintain the invariant that `master` trails `develop` (or equivalently, `develop` is always a descendant of `master`)
This creates a small window where developers should not push before CI finishes because:
- The status of `develop` is not determined, don't compound on red
- This will break the invariant that `master` can fast-forward to `develop`

While we trust ourselves to be pretty disciplined, we would like CI to be at least a bit more resilient to human errors ("oops PM just pushed a README change to master" or "oops the new hire pushed to develop before CI finishes while her pair is on a restroom break").

## Proposal
We propose to add a `merge` boolean parameter. When it's set to true, e.g. with the following `put` step:
```yaml
  - put: head
    params:
      repository: master
      merge: true
```
Then the git resource generates a new version as follows:

### Case 1: `head` can be fast-forwarded to `master`
There is no new version, the put results in exactly the same version as in `head` and `master`

### Case 2: `head` contains commits that are not reachable from `master`
The new version is a merge commit, such that
0. Its first parent is the head of `head`; and
0. its second parent is the head commit of `master`

Similarly to `rebase`,  if pushing fails with non-fast-forward, continuously attempt re-merging and pushing.

## Example

**Given** the following resource definitions in a pipeline:
```yaml
- name: head
  type: git
  source:
    uri: git@example.com/repo
    branch: develop
- name: develop
  type: git
  source:
    uri: https://example.com/repo
    branch: develop
- name: master
  type: git
  source:
    uri: git@example.com/repo
    branch: master
```
**And** the following steps in the promotion job
```yaml
plan:
  - aggregate:
    - put: version
      params:
        bump: minor
    - get: develop
      passed: [unit, integration]
  - task: commit_new_version
    config:
      inputs:
        - name: version
        - name: develop
      outputs:
        - name: bumped
  - put: master
    params:
      repository: bumped
      merge: true
  - put: head
    params:
      repository: master
      merge: true
```
**Then** the job can maintain the invariant that `master` can fast-forward to `develop`.
